name: OneBrain

description: "A new Flutter project."

publish_to: 'none'

version: 1.2.1+71

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  overlay_support: ^2.1.0 
  flutter_svg: ^2.2.1
  easy_localization: ^3.0.7+1
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.1
  device_info_plus: ^11.3.3
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  flutter_bloc: ^9.1.0
  firebase_core: ^3.13.0
  widget_and_text_animator: ^1.1.5
  country_picker_pro: ^0.0.5
  country_codes: ^3.3.0
  flutter_otp_text_field: ^1.5.1+1
  pinput: ^5.0.2
  sign_in_with_apple: ^7.0.1
  jwt_decoder: ^2.0.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  pretty_dio_logger: ^1.4.0
  loading_indicator: ^3.1.1
  flutter_side_menu: ^0.5.41
  blur: ^4.0.2
  gradient_borders: ^1.0.1
  gif_view: ^1.0.2
  haptic_feedback: ^0.5.1+1
  page_transition: ^2.2.1
  cupertino_back_gesture: ^0.1.0
  auto_size_text: ^3.0.0
  simple_gradient_text: ^1.3.0
  marquee_text: ^2.5.0+1
  pull_down_button: ^0.10.2
  http: ^1.4.0
  intl: ^0.20.2
  uuid: ^4.5.1
  file_picker: ^10.2.0
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  get: ^4.7.2 
  flutter_highlight: ^0.7.0
  flutter_math_fork: ^0.7.2
  google_sign_in: ^6.2.1
  open_filex: ^4.7.0
  easy_image_viewer: ^1.5.1
  path_provider: ^2.1.5
  webview_flutter: ^4.13.0
  lottie: ^3.3.1
  flutter_smartlook: ^4.1.29
  flutter_native_splash: ^2.4.6
  upgrader: ^11.5.0
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.1
  package_info_plus: ^8.3.1
  fl_chart: ^0.65.0
  video_player: ^2.10.0
  shimmer: ^3.0.0
  speech_to_text: ^7.0.0
  http_parser: ^4.1.2
  saver_gallery: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.3
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/translations/
    - assets/chat_models/
    - assets/lottie/
    - assets/ai_icon/
    - assets/icons/imagePickerIcon.png
    - assets/icons/phoneIcon.png
    - assets/icons/arrowIcon.png
    - assets/icons/cameraIconNew.png
    - assets/icons/callIcon.png
    - assets/icons/logoutIcon.png
    - assets/icons/mailIcon.png
    - assets/icons/subscriptionIconOne.png
    - assets/icons/trashIcon.png
    - assets/icons/activeSessionIcon.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300

# Splash screen config (only Android enabled)
flutter_native_splash:
  color: "#0c1a25"                    # background color (dark gray)
  image: "assets/icons/logo.png"  
  background_image: "assets/icons/bg.png"    # your splash image (must be PNG)

  android: true
  ios: false
  web: false

  android_12:
    image: "assets/icons/logo.png"
    color: "#0c1a25"
    icon_background_color: "#0c1a25"
